/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views;

/**
 *
 * @author gregory
 */
public class TelaPrincipal extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TelaPrincipal.class.getName());

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painelPrincipal = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuArquivo = new javax.swing.JMenu();
        menuArquivoSair = new javax.swing.JMenuItem();
        menuGerenciar = new javax.swing.JMenu();
        menuGerenciarFornecedor = new javax.swing.JMenuItem();
        menuGerenciarCliente = new javax.swing.JMenuItem();
        menuGerenciarUsuario = new javax.swing.JMenuItem();
        menuGerenciarTipoProduto = new javax.swing.JMenuItem();
        menuGerenciarProduto = new javax.swing.JMenuItem();
        menuGerenciarCompra = new javax.swing.JMenuItem();
        menuGerenciarVenda = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout painelPrincipalLayout = new javax.swing.GroupLayout(painelPrincipal);
        painelPrincipal.setLayout(painelPrincipalLayout);
        painelPrincipalLayout.setHorizontalGroup(
            painelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 770, Short.MAX_VALUE)
        );
        painelPrincipalLayout.setVerticalGroup(
            painelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 499, Short.MAX_VALUE)
        );

        menuArquivo.setText("Arquivo");

        menuArquivoSair.setText("Sair");
        menuArquivoSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuArquivoSairActionPerformed(evt);
            }
        });
        menuArquivo.add(menuArquivoSair);

        jMenuBar1.add(menuArquivo);

        menuGerenciar.setText("Gerenciar");

        menuGerenciarFornecedor.setText("Fornecedor");
        menuGerenciarFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuGerenciarFornecedorActionPerformed(evt);
            }
        });
        menuGerenciar.add(menuGerenciarFornecedor);

        menuGerenciarCliente.setText("Cliente");
        menuGerenciarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuGerenciarClienteActionPerformed(evt);
            }
        });
        menuGerenciar.add(menuGerenciarCliente);

        menuGerenciarUsuario.setText("Usuario");
        menuGerenciarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuGerenciarUsuarioActionPerformed(evt);
            }
        });
        menuGerenciar.add(menuGerenciarUsuario);

        menuGerenciarTipoProduto.setText("Tipo de Produto");
        menuGerenciarTipoProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuGerenciarTipoProdutoActionPerformed(evt);
            }
        });
        menuGerenciar.add(menuGerenciarTipoProduto);

        menuGerenciarProduto.setText("Produto");
        menuGerenciarProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuGerenciarProdutoActionPerformed(evt);
            }
        });
        menuGerenciar.add(menuGerenciarProduto);

        menuGerenciarCompra.setText("Compra");
        menuGerenciarCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuGerenciarCompraActionPerformed(evt);
            }
        });
        menuGerenciar.add(menuGerenciarCompra);

        menuGerenciarVenda.setText("Venda");
        menuGerenciarVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuGerenciarVendaActionPerformed(evt);
            }
        });
        menuGerenciar.add(menuGerenciarVenda);

        jMenuBar1.add(menuGerenciar);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelPrincipal)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(painelPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuArquivoSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuArquivoSairActionPerformed
        // TODO add your handling code here:
        System.exit(1);
    }//GEN-LAST:event_menuArquivoSairActionPerformed

    private void menuGerenciarTipoProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuGerenciarTipoProdutoActionPerformed
        // TODO add your handling code here:
        TelaTipoProduto tela = new TelaTipoProduto();
        painelPrincipal.add(tela);
        tela.setVisible(true);
    }//GEN-LAST:event_menuGerenciarTipoProdutoActionPerformed

    private void menuGerenciarProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuGerenciarProdutoActionPerformed
        // TODO add your handling code here:
        TelaProduto tela = new TelaProduto();
        painelPrincipal.add(tela);
        tela.setVisible(true);                
    }//GEN-LAST:event_menuGerenciarProdutoActionPerformed

    private void menuGerenciarFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuGerenciarFornecedorActionPerformed
        TelaFornecedor tela = new TelaFornecedor();
        painelPrincipal.add(tela);
        tela.setVisible(true);
    }//GEN-LAST:event_menuGerenciarFornecedorActionPerformed

    private void menuGerenciarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuGerenciarClienteActionPerformed
        TelaCliente tela = new TelaCliente();
        painelPrincipal.add(tela);
        tela.setVisible(true);
    }//GEN-LAST:event_menuGerenciarClienteActionPerformed

    private void menuGerenciarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuGerenciarUsuarioActionPerformed
        TelaUsuario tela = new TelaUsuario();
        painelPrincipal.add(tela);
        tela.setVisible(true);
    }//GEN-LAST:event_menuGerenciarUsuarioActionPerformed

    private void menuGerenciarCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuGerenciarCompraActionPerformed
        TelaCompra tela = new TelaCompra();
        painelPrincipal.add(tela);
        tela.setVisible(true);
    }//GEN-LAST:event_menuGerenciarCompraActionPerformed

    private void menuGerenciarVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuGerenciarVendaActionPerformed
        TelaVenda tela = new TelaVenda();
        painelPrincipal.add(tela);
        tela.setVisible(true);
    }//GEN-LAST:event_menuGerenciarVendaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new TelaPrincipal().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu menuArquivo;
    private javax.swing.JMenuItem menuArquivoSair;
    private javax.swing.JMenu menuGerenciar;
    private javax.swing.JMenuItem menuGerenciarCliente;
    private javax.swing.JMenuItem menuGerenciarCompra;
    private javax.swing.JMenuItem menuGerenciarFornecedor;
    private javax.swing.JMenuItem menuGerenciarProduto;
    private javax.swing.JMenuItem menuGerenciarTipoProduto;
    private javax.swing.JMenuItem menuGerenciarUsuario;
    private javax.swing.JMenuItem menuGerenciarVenda;
    private javax.swing.JDesktopPane painelPrincipal;
    // End of variables declaration//GEN-END:variables
}
